### ISSUE TITLE
Through service worker is not a function

### ISSUE THREAD

**Issue by Vibeesarma** [tatethurston/next-service-worker#6]
![image](https://github.com/tatethurston/next-service-worker/assets/77588716/99a3a7fa-5fa1-4351-b5b3-f52c2590702d)

**Comment by tatethurston** [comment]
@Vibeesarma Could you share your next.config.js and your dependency lock file (npm/yarn/pnpm)?

**Comment by tatethurston** [comment]
@Vibeesarma LMK if this issue is present for you on the latest version of this library (1.0.0).
